/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as AdminIndexImport } from './routes/admin/index'
import { Route as AdminRequestsImport } from './routes/admin/requests'
import { Route as AdminArchiveImport } from './routes/admin/archive'
import { Route as AdminHuyImport } from './routes/admin/Huy'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AdminIndexRoute = AdminIndexImport.update({
  path: '/admin/',
  getParentRoute: () => rootRoute,
} as any)

const AdminRequestsRoute = AdminRequestsImport.update({
  path: '/admin/requests',
  getParentRoute: () => rootRoute,
} as any)

const AdminArchiveRoute = AdminArchiveImport.update({
  path: '/admin/archive',
  getParentRoute: () => rootRoute,
} as any)

const AdminHuyRoute = AdminHuyImport.update({
  path: '/admin/Huy',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/admin/Huy': {
      preLoaderRoute: typeof AdminHuyImport
      parentRoute: typeof rootRoute
    }
    '/admin/archive': {
      preLoaderRoute: typeof AdminArchiveImport
      parentRoute: typeof rootRoute
    }
    '/admin/requests': {
      preLoaderRoute: typeof AdminRequestsImport
      parentRoute: typeof rootRoute
    }
    '/admin/': {
      preLoaderRoute: typeof AdminIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  AdminHuyRoute,
  AdminArchiveRoute,
  AdminRequestsRoute,
  AdminIndexRoute,
])

/* prettier-ignore-end */
